### ISSUE TITLE
Merging other guides

### ISSUE THREAD

**Issue by NarryG** [rekyuu/speedfuns#13]
If I submit a pull request with up to date guides for TPE/genocide, would you be up for merging them so there'd be a place with guides that are actually kept up to date?

**Comment by rekyuu** [comment]
TPE is being kept up to date though???

If you'd like to add genocide, feel free

**Comment by NarryG** [comment]
I'm tired and I meant to write neutral/genocide lol

**Comment by rekyuu** [comment]
Oh then of course, go right ahead

**Comment by NarryG** [comment]
Also completely unrelated, but I'm currently getting the script that determines fleeing from Mirrawrs. In the demo, the formula is  

```
runvalue= (random(100) + global.lv*2 - global.battlelv*2 + 10*global.turn)
if runvalue > 50 then
   {
   runaway=1
```

Which would leave you with a 52% chance first turn (since first turn is turn 0) which seems way too high.  
I PM'd asking for an up to date script and I'll add the calculation to the TPE guide once I get the script.
