### ISSUE TITLE
[Readme.md]

### ISSUE THREAD

**Issue by CrimsonFork** [rekyuu/speedfuns#17]
It **IS** possible to [get killed by Toriel](https://m.youtube.com/watch?v=LW5gf-G70xo).

**Comment by MCPlayer1020** [comment]
It is, it is more noted that this was intentional so there was an easter egg lingering.
For this, yes it is possible to be killed by Toriel, although semi hard to.

**Comment by CrimsonFork** [comment]
Fun fact, when I started playing Undertale Inwas so bad at Undertale that I managed to get killed by her while attempting a no-hit run (just the battle).

On May 23, 2018 5:25:40 PM GMT+02:00, MCPlayer1020 <notifications@github.com> wrote:
>It is, it is more noted that this was intentional so there was an
>easter egg lingering.
>For this, yes it is possible to be killed by Toriel, although semi hard
>to.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/speedfuns/undertale/issues/17#issuecomment-391389317

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
